###
PUT http://localhost:8080/deposit
Content-Type: application/json

// 일반 계좌
//{
//  "userName": "test",
//  "memo" : "",
//  "accountNumber": "111",
//  "status": "DEPOSIT",
//  "balance": 100
//}

// 적금 계좌
{
  "userName": "test",
  "memo" : "적금계좌",
  "accountNumber": "333",
  "status": "DEPOSIT",
  "balance": 10000
}

###
PUT http://localhost:8080/withdrawal
Content-Type: application/json

// 일반 계좌
{
  "userName": "test",
  "memo" : "",
  "accountNumber": "111",
  "status": "WITHDRAWAL",
  "balance": 200000
}

// 적금 계좌
//{
//  "userName": "test",
//  "memo" : "적금계좌",
//  "accountNumber": "333",
//  "status": "WITHDRAWAL",
//  "balance": 10000
//}

###
GET http://localhost:8080/user/account
Content-Type: application/json

// 일반 계좌
//{
//  "userName": "test",
//  "accountNumber": "111",
//  "bankName": "우리은행"
//}

// 적금 계좌
{
  "userName": "test",
  "accountNumber": "333",
  "bankName": "하나은행"
}

###
GET http://localhost:8080/user/accounts?user=test




